### ISSUE TITLE
Include both x86 and x64 runtimes in the .NET Desktop Bundle

### ISSUE THREAD

**Issue by dagood** [dotnet/windowsdesktop#136]
For 3.0, we have this matrix of installers built in dotnet/core-setup that potentially all need to be installed to get WindowsDesktop apps to run:

|   | x64 | x86 |
| --- | --- | --- |
.NET Core Runtime | x | x
.NET Desktop Runtime | x | x

In 3.1, this matrix is simplifying to:

|   | x64 | x86 |
| --- | --- | --- |
.NET Desktop Runtime | x | x

The ideal is bundling both architectures in one installer, getting us to:

|   |
| --- |
.NET Desktop Runtime

This enables non-technical users to get FDE WPF/WinForms apps running on their machines without forcing them to:
* determine which arch they need
* determine they need to install both because they don't know which one is required.

This is somewhat of a challenge from an infra point of view: x86 and x64 build on separate machines right now, but the MSIs have to all be shuffled to the same machine (or built on the same machine) to bundle them together.

More discussion about this simplification: https://github.com/dotnet/core-setup/issues/8368.

**Comment by Symbai** [comment]
I highly appreciate the amazing effort your team is doing to simplify the end user experience. But there is an issue when combining the architectures when:

1. A developer has a 64bit machine
2. The developer compiles his application explicitly as 32bit / x86
3. The user has a 64bit machine
4. The user downloads the installer with combined architectures
5. The installer will likely install the 64bit runtime because its running on a 64bit machine

Problem: The 32bit application won't start as it doesn't run on a 64bit runtime. (Tested myself on .NET Core 3.0 plain Winforms application). It explicitly requires a 32bit runtime. 

Maybe making the installer installing 32bit **and** 64bit runtime when detecting a 64bit machine?

**Comment by dagood** [comment]
> Maybe making the installer installing 32bit **and** 64bit runtime when detecting a 64bit machine?

I missed actually mentioning it, but yes, that's the plan for exactly that reason. 😄 Thanks for writing out the scenario, it's useful to have listed here.

**Comment by RussKie** [comment]
@dagood is this still a thing?

**Comment by dagood** [comment]
@NikolaMilosavljevic

**Comment by NikolaMilosavljevic** [comment]
@RussKie my team is not tracking this work. Installer infrastructure is now mostly in Arcade and all teams that consume it (i.e. WinForms, WPF) can make the changes as appropriate.

**Comment by AraHaan** [comment]
I would love this, however should arm64 be included with this (and have it only attempt to display or install it if their OS supports arm64)

This would be great however for the .NET SDK itself as well as the other places where installers are officially made as well too.
